import React from 'react'

export default function Loader(props) {
  return (
    <div className={`h-100 w-100 position-fixed d-flex zindex-1000 bg-opacity-50 bg-blur-5`}>
      <InfinityLoader color={props.color} />
    </div>
  )
}

const InfinityLoader = ({ color }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="200px"
    height="200px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    style={{ margin: 'auto', background: 'rgba(255, 255, 255, 0)', display: 'block', shapeRendering: 'auto' }}>
    <path
      fill="none"
      stroke={color.color}
      strokeWidth="8"
      strokeDasharray="42.76482137044271 42.76482137044271"
      d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z"
      strokeLinecap="round"
      style={{ transform: 'scale(1)', transformOrigin: '50px 50px' }}>
      <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="2s" keyTimes="0;1" values="0;256.58892822265625"></animate>
    </path>
    {/* [ldio] generated by https://loading.io/ */}
  </svg>
);


